---
- name: install deb packages
  apt:
    deb: "{{ item.url }}"
  with_items: "{{ deb_packages }}"

- name: install apt packages
  apt:
    name: "{{ item.name }}"
    update_cache: yes
    state: latest
  with_items: "{{ apt_packages }}"

- name: install snap packages
  command: "snap install {{ item.name }} --classic --no-wait"
  with_items: "{{ snap_packages }}"
  
- name: Download and Install packages using scripts
  command: "{{ item.command }}"
  with_items: "{{ script_install_packages }}"