---
version: "2"

networks:
  media-server:

services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: unless-stopped
    networks:
      - media-server
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    environment:
      - TZ=Africa/Cairo
      - PUID=1000
      - PGID=1000
      - USER=username #optional
      - PASS=password #optional
    volumes:
      - /home/nathanf/media-server/config/transmission:/var/lib/transmission-daemon/info
      #set transmission or sonarr download folder to /downloads
      - /home/nathanf/media-server/downloads/complete:/downloads
      - /home/nathanf/media-server/downloads/temp:/var/lib/transmission-daemon/incomplete

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
      - UMASK_SET=022 #optional
    volumes:
      - /home/nathanf/media-server/config/sonarr:/config
      - /home/nathanf/media-server/storage/series:/tv
      - /home/nathanf/media-server/downloads/complete:/downloads
    ports:
      - 8989:8989
    networks:
      - media-server
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    depends_on:
      - plex
    ports:
      - 7878:7878
    networks:
      - media-server
    environment:
      - TZ=Africa/Cairo
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/nathanf/media-server/config/radarr:/config
      - /home/nathanf/media-server/storage/movies:/movies
      - /home/nathanf/media-server/downloads/complete:/downloads

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    networks:
      - media-server
    environment:
      - TZ=Africa/Cairo
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/nathanf/media-server/config/jackett:/config
      - /home/nathanf/media-server/downloads/blackhole:/downloads

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=Africa/Cairo
      - PLEX_CLAIM=
      - PLEX_UID=1000
      - PLEX_GID=1000
    ports:
      - 3000:32400
    networks:
      - media-server
    volumes:
      - /home/nathanf/media-server/config/plex:/config
      - /home/nathanf/media-server/transcode:/transcode
      - /home/nathanf/media-server/storage:/data

  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /home/nathanf/media-server/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

