---
- name: install apt packages
  apt:
    name: "{{ item.name }}"
    update_cache: yes
    state: latest
  with_items: "{{ apt_packages }}"

- name: install snap packages
  command: "snap install {{ item.name }} --classic --no-wait"
  with_items: "{{ snap_packages }}"
