---
- name: "install docker dependencies"
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - software-properties-common

- name: download docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: install docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version }} stable"
    state: present

- name: install docker engine
  apt:
    name: docker-ce
    state: present
    update_cache: yes
