---
- name: install apt repository keys
  apt_key:
    url: "{{ item.apt_key }}"
  with_items: "{{ apt_repository }}" 

- name: install apt repository
  apt_repository:
    repo: "{{ item.apt_repo }}"
    state: present
  with_items: "{{ apt_repository }}"

- name: install apt packages
  apt:
    name: "{{ item.name }}"
    update_cache: yes
    state: latest
  with_items: "{{ apt_packages }}"

- name: install snap packages
  command: "snap install {{ item.name }} --classic --no-wait"
  with_items: "{{ snap_packages }}"
