---
apt_packages:
  - name: curl
  - name: vim
  - name: build-essential
  - name: zsh
  - name: tilda

snap_packages:
  - name: slack
  - name: skype
  - name: sublime-text
  - name: chromium
  - name: mailspring
  - name: keepassxc